# Generated by Django 5.1.1 on 2024-09-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
